services:
  open-webui:
    build:
      context: .
      args:
        BUILDPLATFORM: 'linux/amd64'
      dockerfile: Dockerfile
    image: hongdinh/open-webui:${WEBUI_DOCKER_TAG:-latest}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT:-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    restart: unless-stopped

volumes:
  open-webui: {}